
language: python

python:
    - 2.7
    - 3.5
    - 3.6
install:
  -pip install -r MyDiary_Backend/requirements.txt
# install dependencies
install:
  - pip install codecov

# run scripts
script:
  - coverage erase
  - coverage run test_webapp.py && coverage html

after_success:
  - codecov

script:
    - pylint --output-format=text manage.py
