
language: python

python:
   
    - 3.6


install:
  - pip install codecov
  - pip install pylint
  - pip install -r FlaskApi/requirements.txt

# run scripts
script:
  - coverage erase
  - coverage run test_user.py && coverage html

after_success:
  - codecov

script:
    - pylint --output-format=text FlaskApi/app.py
